import type { ReactNode } from 'react'
import type { Band, Confidence, Constraint, StatusPill as StatusPillT } from '../api/types'
import { inr, num, pct } from '../lib/format'

/* ------------------------------------------------------------------ icons (inline, no CDN) */
export type IconName = 'check' | 'alert' | 'eye' | 'info' | 'up' | 'down' | 'dot' | 'lock' | 'flask' | 'spark'

const PATHS: Record<IconName, string> = {
  check: 'M20 6 9 17l-5-5',
  alert: 'M12 9v4m0 4h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z',
  eye: 'M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7-10-7-10-7Zm10 3a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z',
  info: 'M12 16v-4m0-4h.01M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Z',
  up: 'M7 14l5-5 5 5',
  down: 'M7 10l5 5 5-5',
  dot: 'M12 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z',
  lock: 'M7 11V8a5 5 0 0 1 10 0v3M5 11h14v10H5z',
  flask: 'M9 3h6M10 3v6L5 19a2 2 0 0 0 1.8 3h10.4A2 2 0 0 0 19 19l-5-10V3',
  spark: 'M12 3v4m0 10v4M3 12h4m10 0h4M6 6l2.5 2.5M15.5 15.5 18 18M18 6l-2.5 2.5M8.5 15.5 6 18',
}

export function Icon({ name, size = 14, color = 'currentColor' }: { name: IconName; size?: number; color?: string }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2.2"
      strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d={PATHS[name]} />
    </svg>
  )
}

/* ------------------------------------------------------------------ chips */
type ChipKind = 'synthetic' | 'illustrative' | 'estimated' | 'green' | 'yellow' | 'red' | 'blue' | 'ghost'
const CHIP_ICON: Partial<Record<ChipKind, IconName>> = {
  synthetic: 'flask', illustrative: 'info', estimated: 'spark',
  green: 'check', yellow: 'alert', red: 'alert', blue: 'info',
}

/** The honesty label every number-bearing panel carries (SPEC §9). */
export function TruthLabel({ kind = 'estimated' }: { kind?: 'synthetic' | 'illustrative' | 'estimated' }) {
  const text = { synthetic: 'Synthetic', illustrative: 'Illustrative', estimated: 'Estimated' }[kind]
  const title = {
    synthetic: 'Generated by the ProfitPilot simulator — no real seller or Meesho data',
    illustrative: 'An input assumption for the prototype, not a measured cost',
    estimated: 'Model output with an uncertainty range — not a guarantee',
  }[kind]
  return <Chip kind={kind} title={title}>{text}</Chip>
}

export function Chip({ kind = 'ghost', children, title, icon }: { kind?: ChipKind; children: ReactNode; title?: string; icon?: IconName }) {
  const ic = icon ?? CHIP_ICON[kind]
  return (
    <span className={`chip chip-${kind}`} title={title}>
      {ic ? <Icon name={ic} /> : null}
      {children}
    </span>
  )
}

export function ConfidencePill({ label, block, compact = false }: { label: Confidence; block?: { n_eff: number; band_width: number; extrapolation_pct: number; rule: string }; compact?: boolean }) {
  const kind = label === 'High' ? 'green' : label === 'Medium' ? 'yellow' : 'red'
  const title = block
    ? `Rule — ${block.rule}\nComparable weight (n_eff): ${num(block.n_eff, 0)}\nRange width: ${pct(block.band_width, 0)}\n${
        block.extrapolation_pct > 0 ? `Outside the observed price range by ${pct(block.extrapolation_pct, 0)}` : 'Inside the observed price range'
      }`
    : 'Confidence reflects comparable evidence, range width and model calibration'
  return (
    <Chip kind={kind} title={title}>
      {label} confidence{compact ? '' : ' ★'}
    </Chip>
  )
}

export function StatusPill({ status }: { status: StatusPillT }) {
  const kind = status.id === 'losing' ? 'red' : status.id === 'watch' ? 'yellow' : 'green'
  const icon: IconName = status.icon === 'alert' ? 'alert' : status.icon === 'eye' ? 'eye' : 'check'
  return <Chip kind={kind} icon={icon}>{status.label}</Chip>
}

/* ------------------------------------------------------------------ numbers */
export function RangeNumber({ value, format = (v: number) => inr(v), size = 'lg', tone = '' }: {
  value: Band
  format?: (v: number) => string
  size?: 'lg' | 'sm'
  tone?: '' | 'good' | 'bad'
}) {
  return (
    <div className={`metric ${tone === 'good' ? 'metric-good' : tone === 'bad' ? 'metric-bad' : 'metric-primary'}`}>
      <div className={`value ${size === 'sm' ? 'sm' : ''}`}>{format(value.p50)}</div>
      <div className="range">range {format(value.p10)} – {format(value.p90)}</div>
    </div>
  )
}

export function MetricBlock({ label, value, format, note, tone, size = 'sm' }: {
  label: string
  value: Band | number
  format?: (v: number) => string
  note?: string
  tone?: '' | 'good' | 'bad'
  size?: 'lg' | 'sm'
}) {
  const f = format ?? ((v: number) => inr(v))
  const band: Band = typeof value === 'number' ? { p10: value, p50: value, p90: value } : value
  return (
    <div className="metric">
      <div className="label">{label}</div>
      <div className={`value ${size === 'sm' ? 'sm' : ''} ${tone === 'good' ? 'metric-good' : tone === 'bad' ? 'metric-bad' : ''}`}>
        {f(band.p50)}
      </div>
      <div className="range">{typeof value === 'number' ? (note ?? '') : `range ${f(band.p10)} – ${f(band.p90)}`}</div>
    </div>
  )
}

/* ------------------------------------------------------------------ layout atoms */
export function Card({ title, right, children, note, className = '' }: {
  title?: ReactNode
  right?: ReactNode
  children: ReactNode
  note?: ReactNode
  className?: string
}) {
  return (
    <section className={`card ${className}`}>
      {title ? (
        <header className="card-head">
          <h3>{title}</h3>
          <span className="spacer" />
          {right}
        </header>
      ) : null}
      <div className="card-pad">{children}</div>
      {note ? <div className="card-note">{note}</div> : null}
    </section>
  )
}

export function Skeleton({ height = 16, width = '100%', mb = 8 }: { height?: number; width?: string | number; mb?: number }) {
  return <div className="skeleton" style={{ height, width, marginBottom: mb }} />
}

export function LoadingCard({ lines = 4, title }: { lines?: number; title?: string }) {
  return (
    <Card title={title ?? 'Loading…'}>
      {Array.from({ length: lines }).map((_, i) => <Skeleton key={i} height={i === 0 ? 28 : 14} width={i === 0 ? '45%' : '100%'} />)}
    </Card>
  )
}

export function ErrorState({ message, onRetry, requestId }: { message: string; onRetry?: () => void; requestId?: string | null }) {
  return (
    <div className="note note-bad" role="alert">
      <Icon name="alert" color="#b91c1c" />
      <div>
        <strong>Something went wrong.</strong>
        <div>{message}</div>
        {requestId ? <div className="tiny muted mono">request id {requestId}</div> : null}
        {onRetry ? <button className="btn btn-sm" style={{ marginTop: 8 }} onClick={onRetry}>Try again</button> : null}
      </div>
    </div>
  )
}

export function EmptyState({ title, body, action }: { title: string; body: string; action?: ReactNode }) {
  return (
    <div className="center" style={{ padding: '32px 16px' }}>
      <h3>{title}</h3>
      <p className="muted small">{body}</p>
      {action}
    </div>
  )
}

/* ------------------------------------------------------------------ constraints */
export function ConstraintList({ constraints, limit = 9 }: { constraints: Constraint[]; limit?: number }) {
  return (
    <div>
      {constraints.slice(0, limit).map((c) => (
        <div key={c.id} data-constraint={c.id} data-pass={String(c.pass_)} className="row-tight"
          style={{ justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px dashed var(--line)' }}>
          <span className="row-tight small">
            <Icon name={c.pass_ ? 'check' : 'alert'} color={c.pass_ ? '#15803d' : '#b91c1c'} />
            {c.label}
            {c.note ? <span className="tiny muted">· {c.note}</span> : null}
          </span>
          <span className={`small ${c.pass_ ? 'muted' : ''}`} style={{ color: c.pass_ ? undefined : 'var(--red-700)' }}>
            {c.unit === 'share' ? `${pct(c.actual)} vs ${pct(c.required)} cap` :
             c.unit === '₹/kept order' ? `${inr(c.actual)} vs ${inr(c.required)} floor` :
             c.unit === 'orders/day' ? `${num(c.actual, 1)} vs ${num(c.required, 0)}/day floor` :
             c.unit === '₹' ? `${inr(c.actual)} (limit ${inr(c.required)})` :
             c.unit === 'units' ? `${num(c.actual, 0)} vs ${num(c.required, 0)} needed` :
             c.pass_ ? 'passes' : 'fails'}
          </span>
        </div>
      ))}
    </div>
  )
}

export function ConstraintChipRow({ constraints }: { constraints: Record<string, boolean> }) {
  const FAIL_LABEL: Record<string, string> = {
    contribution_floor: 'contribution floor', volume_floor: 'volume floor', return_cap: 'return cap',
    corridor: 'market corridor', max_price_move: '12% step cap', confidence: 'confidence',
    inventory: 'inventory cover', cash: 'working capital',
  }
  return (
    <div className="pill-row">
      {Object.entries(constraints).map(([k, ok]) => (
        <Chip key={k} kind={ok ? 'green' : 'red'} title={ok ? 'passed at this price' : 'failed at this price'}>
          {FAIL_LABEL[k] ?? k}: {ok ? 'passes' : 'fails'}
        </Chip>
      ))}
    </div>
  )
}

/* ------------------------------------------------------------------ guardrails + about */
export function GuardrailBar({ guardrails }: { guardrails: Record<string, string | boolean> }) {
  return (
    <div className="note note-info">
      <Icon name="lock" color="#1d4ed8" />
      <div className="small">
        <strong>Guardrails.</strong>{' '}
        Recommendation only — ProfitPilot never changes a live price. Maximum{' '}
        {typeof guardrails.max_price_move === 'number' ? pct(guardrails.max_price_move, 0) : '12%'} price move per step.
        The market corridor is enforced; nothing below your contribution floor is recommended. No buyer-level or personalised pricing.
        Low-confidence advice is never shown as a recommendation.
      </div>
    </div>
  )
}

export function AboutFootnote() {
  return (
    <footer className="wrap tiny muted wrap-wide" style={{ paddingTop: 0 }}>
      <div className="hr" />
      <p>
        <strong>What this is.</strong> A competition prototype. Every seller, listing, order and cost in
        ProfitPilot is synthetic, generated by an offline simulator seeded at <span className="mono">20260928</span>.
        No Meesho data, systems or internal APIs are used, and no Meesho number is reproduced here — with
        one exception, quoted once as motivation for looking beyond headline sales: Meesho's company-reported
        FY26 NMV was about 58.8% of GMV, i.e. roughly two-fifths of what a buyer pays is not product value.
      </p>
      <p>
        Cost inputs are <em>Illustrative</em>; model outputs are <em>Estimated</em> with p10–p90 ranges; simulator
        outputs are <em>Synthetic</em>. Treat every number as a demonstration of method, not a measurement.
      </p>
    </footer>
  )
}
