import { Link, useParams } from 'react-router-dom'
import { api } from '../api/client'
import type { CustomerListing as CL } from '../api/types'
import { useAsync } from '../state/session'
import { Card, Chip, ErrorState, Icon, LoadingCard, TruthLabel } from '../components/ui'
import { inr } from '../lib/format'

export default function CustomerListing() {
  const { skuId = 'K-101' } = useParams()
  const cl = useAsync<CL>(() => api.customerListing(skuId), [skuId])

  if (cl.loading && !cl.data) return <div className="wrap"><LoadingCard title="Listing" lines={5} /></div>
  if (cl.error) return <div className="wrap"><ErrorState message={cl.error} onRetry={cl.refetch} /></div>
  if (!cl.data) return null
  const l = cl.data.listing

  return (
    <div className="wrap">
      <div className="crumbs"><Link to="/login">Sign in</Link> · buyer view</div>
      <div className="row-tight" style={{ justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
        <div>
          <h1>{l.name}</h1>
          <p className="muted small" style={{ margin: 0 }}>
            {l.category} · sold from {l.seller_city} · <span className="mono">{l.sku_id}</span>
          </p>
        </div>
        <TruthLabel kind="synthetic" />
      </div>

      <div className="grid-2">
        <Card title="What you pay" right={<Chip kind="ghost">one price for everyone</Chip>}>
          <div className="row-tight" style={{ justifyContent: 'space-between', alignItems: 'baseline' }}>
            <span className="big" style={{ fontSize: 30, fontWeight: 650 }}>{inr(l.price)}</span>
            <Chip kind="green">{l.availability}</Chip>
          </div>
          <div className="hr" />
          <div className="row-tight" style={{ justifyContent: 'space-between' }}>
            <span className="small">Rating</span><span className="small">{l.rating} ★ from {l.review_count.toLocaleString('en-IN')} reviews</span>
          </div>
          <div className="row-tight" style={{ justifyContent: 'space-between', marginTop: 6 }}>
            <span className="small">Delivery</span><span className="small">{l.delivery_estimate}</span>
          </div>
          <div className="row-tight" style={{ justifyContent: 'space-between', marginTop: 6 }}>
            <span className="small">Returns</span><span className="small">{l.return_policy}</span>
          </div>
          <div className="note note-info" style={{ marginTop: 12 }}>
            <Icon name="lock" color="#1d4ed8" />
            <span className="small"><strong>{l.price_notice}</strong></span>
          </div>
        </Card>

        <div className="col">
          <Card title="How you can pay" right={<Chip kind="ghost">no fee to you</Chip>}>
            {l.payment_options.map((p) => (
              <div key={p.id} className="row-tight" style={{ justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px dashed var(--line)' }}>
                <span className="small"><strong>{p.label}</strong><div className="tiny muted">{p.note}</div></span>
                <Chip kind={p.id === 'prepaid' ? 'green' : 'yellow'}>{p.id}</Chip>
              </div>
            ))}
            <p className="tiny muted" style={{ marginTop: 10 }}>
              Prepaid orders fail less often in this simulator, which is why the seller may nudge toward them — but the
              price shown to you does not change with how you pay, what you browsed, or who you are.
            </p>
          </Card>

          <Card title="Why this page exists" right={<Chip kind="ghost">transparency demo</Chip>}>
            <p className="small" style={{ margin: 0 }}>
              A pricing system that only optimises the seller&apos;s margin can quietly push cost onto the buyer — through
              hidden fees, worse packing, or personalised prices. ProfitPilot&apos;s seller tools are constrained to the
              market corridor and to a single public price, and this page is where that constraint is visible.
            </p>
            <ul className="small" style={{ margin: '10px 0 0 18px' }}>
              <li>No buyer-level pricing anywhere in the system.</li>
              <li>No urgency or scarcity messaging generated by the model.</li>
              <li>Return and RTO costs are shown to the seller, not hidden in your price.</li>
            </ul>
          </Card>
        </div>
      </div>
    </div>
  )
}
