"""Stage 1: generate the synthetic dataset from the ground-truth world.

Deterministic (SEED fixed). Writes:
  data/synthetic/skus.csv           ~600 SKUs (9 hand-authored demo SKUs + generated)
  data/synthetic/sku_daily_obs.csv  ~36k SKU-days (the M1/M2 training table)
  data/synthetic/order_events.csv   ~28k order-level rows (M3/M4 training table)
  data/synthetic/README.md          provenance + the hidden-confounder description

Nothing here is Meesho data. Everything is generated by `app.ml.world` with known ground truth.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.ml import catalogue as cat          # noqa: E402
from app.ml.world import BASE, EXT, econ, sigmoid, world  # noqa: E402

SEED = cat.SEED
DAYS = 60
ORDER_DAYS = 30
N_STRATIFIED = 140         # extra SKUs with order-level history: M3/M4 estimate SKU-level quality
                           # coefficients (image, packaging) from these clusters, so too few of them
                           # attenuates the estimates against the category effects.
OUT = ROOT / "data" / "synthetic"


def world_params(sku: dict) -> dict:
    """Map a catalogue SKU row to ground-truth world parameters."""
    cfg = cat.CATEGORIES[sku["category"]]
    return dict(
        BASE,
        cost=float(sku["cost"]), pack_cost=float(sku["pack_cost"]), fwd=float(sku["fwd_shipping"]),
        rev=float(sku["rev_shipping"]), restock=float(sku["restock_cost"]), pay_var=float(sku["pay_var"]),
        ads=float(sku["ad_cost"]), gst=cat.gst_rate_for(sku["category"], float(sku["ref_price"])),
        pref=float(sku["ref_price"]), comp=float(sku["competitor_price"]), comp_w=1.0,
        rating=float(sku["rating"]), img=float(sku["image_quality"]), impr=int(sku["impressions_per_day"]),
        a0=cfg["a0"], beta=cfg["beta"], cat_rto=cfg["cat_rto"], cat_ret=cfg["cat_ret"],
        fit_risk=cfg["fit_risk"], pack_q=float(sku["pack_quality"]),
        canc=float(sku["cancel_rate"]), z3=float(sku["zone3_share"]),
        seller_hist=float({s["seller_id"]: s["hist"] for s in cat.SELLERS}.get(sku["seller_id"], 0.1)),
    )


def demand_shock(category: str, week: int) -> float:
    """The hidden confounder: a category-level weekly demand shock, never observed as a feature.

    Deterministic in (category, week) so tests can regenerate it.
    """
    h = abs(hash((category, week, SEED))) % (2 ** 31)
    rng = np.random.default_rng(h)
    return float(rng.normal(0.0, 0.55))


def seasonality(day_idx: int, dow: int) -> float:
    """Weekday effect + a festival bump (Illustrative)."""
    weekend = 1.18 if dow >= 5 else (0.97 if dow < 3 else 1.04)
    festival = 1.55 if 44 <= day_idx <= 46 else 1.0
    return weekend * festival


def ctr_for(s: dict) -> float:
    """Impression -> click rate. Depends on image quality and rating (synthetic stand-in for
    creative quality) so the diagnosis funnel can attribute a weak CTR to a weak primary image."""
    return sigmoid(-2.95 + 1.8 * (s["img"] - 0.5) + 0.6 * (s["rating"] - 4.0))


def gen_daily(sku: dict, s: dict, rng: np.random.Generator) -> pd.DataFrame:
    rows = []
    is_demo = sku["sku_id"] in cat.DEMO_SKU_IDS
    lo, hi = sku["corridor"]
    for d in range(DAYS):
        import datetime as dt
        date = dt.date(2026, 7, 1) + dt.timedelta(days=d)
        dow = date.weekday()
        week = d // 7
        shock = demand_shock(sku["category"], week)
        season = seasonality(d, dow)
        impressions = int(rng.negative_binomial(6.0, 6.0 / (6.0 + s["impr"] * season)))
        clicks = int(rng.binomial(max(impressions, 0), min(0.95, ctr_for(s))))
        # --- price path -------------------------------------------------------------------
        if is_demo:
            # demo SKUs sit on a randomised ladder spanning the market corridor (the synthetic
            # stand-in for the randomised price-experiment phase, SPEC 13.1)
            price = float(np.round(s["pref"] * rng.uniform(0.88, 1.12)))
            source = "randomised_ladder"
        elif rng.random() < 0.5:
            price = float(np.round(s["pref"] * rng.uniform(0.88, 1.12)))
            source = "randomised_ladder"
        else:
            # seller's own pricing rule, reacting to the UNOBSERVED demand shock => naive regression bias
            price = float(np.round(s["pref"] * (1.0 - 0.04 * max(shock, 0.0)) * rng.uniform(0.985, 1.015)))
            source = "seller_rule"
        q_eff = s["q_base"] if False else None  # placeholder for clarity
        w = world(s, price)
        q = w["q"] * float(np.exp(0.10 * shock))          # conversion moves with the hidden shock
        p_conv = float(np.clip(q / max(ctr_for(s), 1e-6), 0.0, 0.98))
        orders = int(rng.binomial(clicks, p_conv))
        cod_orders = int(rng.binomial(orders, w["cod"]))
        cancelled = int(rng.binomial(orders, s["canc"]))
        shipped = orders - cancelled
        rto = int(rng.binomial(shipped, w["rto"]))
        delivered = shipped - rto
        returned = int(rng.binomial(delivered, w["ret_c"]))
        kept = delivered - returned
        e = econ(s, price)
        gmv = orders * price
        nmv = kept * price / (1 + s["gst"])
        rows.append(dict(
            sku_id=sku["sku_id"], date=date.isoformat(), price=price, price_source=source,
            impressions=impressions, clicks=clicks,
            ctr=round(clicks / impressions, 5) if impressions else 0.0,
            conversion=round(orders / clicks, 5) if clicks else 0.0,
            orders=orders, cod_orders=cod_orders, cancelled=cancelled, shipped=shipped,
            rto=rto, delivered=delivered, returned=returned, kept=kept,
            traffic_feed_share=round(float(np.clip(rng.normal(0.70, 0.09), 0.2, 0.98)), 3),
            zone3_share=sku["zone3_share"],
            gmv=round(gmv, 2), nmv=round(nmv, 2),
            retained_contribution=round(kept * e["kept_val"] + returned * e["ret_val"] + rto * e["rto_val"], 2),
        ))
    return pd.DataFrame(rows)


def gen_orders(sku: dict, s: dict, rng: np.random.Generator, days: int) -> pd.DataFrame:
    rows = []
    import datetime as dt
    import uuid
    for d in range(days):
        date = dt.date(2026, 9, 1) + dt.timedelta(days=d)
        shock = demand_shock(sku["category"], d // 7)
        season = seasonality(d, date.weekday())
        impressions = int(s["impr"] * season)
        clicks = int(rng.binomial(impressions, ctr_for(s)))
        price = float(np.round(s["pref"] * rng.uniform(0.9, 1.08)))
        w = world(s, price)
        q = w["q"] * float(np.exp(0.10 * shock))
        orders = int(rng.binomial(clicks, float(np.clip(q / max(ctr_for(s), 1e-6), 0, 0.98))))
        for _ in range(orders):
            zone = int(rng.choice([1, 2, 3], p=[0.45, 0.32, 0.23]) + (2 if rng.random() < float(sku["zone3_share"]) else 0))
            zone = min(zone, 3)
            cod = bool(rng.random() < w["cod"])
            cancelled = bool(rng.random() < s["canc"])
            shipped = not cancelled
            rto = bool(shipped and rng.random() < (w["rto_cod"] if cod else w["rto_pp"]))
            delivered = shipped and not rto
            returned = bool(delivered and rng.random() < (w["ret_cod"] if cod else w["ret_pp"]))
            kept = delivered and not returned
            rows.append(dict(
                order_id=str(uuid.uuid5(uuid.NAMESPACE_DNS, f"{sku['sku_id']}-{d}-{len(rows)}")),
                sku_id=sku["sku_id"], ts=f"{date.isoformat()}T{9 + (len(rows) % 11):02d}:{(len(rows) * 7) % 60:02d}:00",
                price=price, payment_mode="COD" if cod else "PREPAID", zone_tier=zone,
                cancelled=int(cancelled), shipped=int(shipped), delivered=int(delivered),
                rto=int(rto), returned=int(returned), kept=int(kept),
                customer_pseudo_id=str(uuid.uuid4()),
            ))
    return pd.DataFrame(rows)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    skus = cat.all_skus()
    sku_rows, daily_frames, order_frames = [], [], []
    for sku in skus:
        s = world_params(sku)
        seed = SEED + (abs(hash(sku["sku_id"])) % 10 ** 6)
        rng = np.random.default_rng(seed)
        cfg = cat.CATEGORIES[sku["category"]]
        row = dict(sku)
        row["corridor_low"], row["corridor_high"] = sku["corridor"]
        row["gst_rate"] = cat.gst_rate_for(sku["category"], float(sku["ref_price"]))
        row["ref_price"] = float(sku["ref_price"])
        row["flags"] = json.dumps(sku["flags"])
        row.pop("corridor")
        sku_rows.append(row)
        daily_frames.append(gen_daily(sku, s, rng))
        if sku["sku_id"] in cat.DEMO_SKU_IDS:
            order_frames.append(gen_orders(sku, s, rng, ORDER_DAYS))

    # stratified order-level sample so M3/M4 can identify category effects
    rng = np.random.default_rng(SEED + 7)
    by_cat: dict[str, list[dict]] = {}
    for sku in skus:
        if sku["sku_id"] in cat.DEMO_SKU_IDS:
            continue
        by_cat.setdefault(sku["category"], []).append(sku)
    picked = []
    for c, lst in by_cat.items():
        picked += list(rng.choice(lst, size=min(N_STRATIFIED // len(by_cat), len(lst)), replace=False))
    for sku in picked:
        rng2 = np.random.default_rng(SEED + (abs(hash(sku["sku_id"])) % 10 ** 6))
        order_frames.append(gen_orders(sku, world_params(sku), rng2, ORDER_DAYS))

    sku_df = pd.DataFrame(sku_rows)
    daily = pd.concat(daily_frames, ignore_index=True)
    orders = pd.concat(order_frames, ignore_index=True)
    sku_df.to_csv(OUT / "skus.csv", index=False)
    daily.to_csv(OUT / "sku_daily_obs.csv", index=False)
    orders.to_csv(OUT / "order_events.csv", index=False)

    (OUT / "README.md").write_text(
        "# Synthetic data\n\n"
        f"Generated by `scripts/generate_data.py` with seed {SEED} from `backend/app/ml/world.py`\n"
        "(the ground-truth world; never called by seller-facing endpoints).\n\n"
        f"- `skus.csv` — {len(sku_df)} SKUs ({len(cat.DEMO_SKU_IDS)} hand-authored demo SKUs)\n"
        f"- `sku_daily_obs.csv` — {len(daily)} SKU-days (M1 demand, M2 payment-mix training table)\n"
        f"- `order_events.csv` — {len(orders)} order-level rows (M3 RTO, M4 return training table)\n\n"
        "**Hidden confounder:** a category-level weekly demand shock drives both conversion and the\n"
        "seller's own price rule on `price_source=seller_rule` days, so a naive regression of orders on\n"
        "price is biased. `price_source=randomised_ladder` days draw the price independently of the\n"
        "shock; they are the synthetic stand-in for the randomised price-experiment phase (roadmap) and\n"
        "are what identify the causal price effect.\n\n"
        "Customer identifiers are random UUIDs. No Meesho data, no PII.\n", encoding="utf-8")

    print(f"skus={len(sku_df)} daily={len(daily)} orders={len(orders)}")
    demo = daily[daily.sku_id.isin(["K-101", "K-207", "K-330", "K-118"])]
    print(demo.groupby("sku_id")[["orders", "kept"]].mean().round(2).to_string())


if __name__ == "__main__":
    main()
